import MainBanner from '../components/MainBanner'
import Head from 'next/head'
import AboutMeBlock from '@/components/aboutMe/AboutMeBlock'
import ProjectsBlock from '@/components/projects/ProjectsBlock'
import ContactBlock from '@/components/contact/ContactBlock'
import Layout from '@/components/Layout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Balazs Csordas | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <MainBanner/>
        <AboutMeBlock/>
        <ProjectsBlock/>
        <ContactBlock/>
      </Layout>
    </>
  )
}
